### ISSUE TITLE
Enhance: Tally the amount of cash when "Press to Collect Cash" button is pressed

### ISSUE THREAD

**Issue by yeojc** [richardz316/vmcs#1]
An enhancement is identified to address this problem and especially to aid the Maintainer. The
system is required to provide an at-a-glance display of the cash amount available, by
denomination, for collection by the Maintainer. This will enable the Maintainer to readily tally
the total cash collected and the total number of coins by denomination displayed in “Show
Total Cash Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute
over system errors.

**Comment by richardz316** [comment]
Tasks:
01. Create new display component to display the total coins to collect.
02. Modify the corresponding display components, controllers, listeners to update/display the cash information of all denominations. 
03. Modify the corresponding display components, controllers, listeners to update/display the quantity and amount of all coins on the display.

**Comment by bendanye** [comment]
I have completed the code and update the design model report. Please verify the changes are correct

**Comment by smitabisoyi** [comment]
Verified the enhancement

**Comment by jarongoh** [comment]
Hi,

    Enhancement has been verified.

    Attached ScreenShots and Testlog.

    Please Validate.

![enhance001](https://user-images.githubusercontent.com/17529208/30175638-d83c17ac-9431-11e7-94a0-71e0a698a060.gif)
![enhance02a](https://user-images.githubusercontent.com/17529208/30175643-dd014348-9431-11e7-8474-8a5e2160740d.GIF)
![enhance02b](https://user-images.githubusercontent.com/17529208/30175646-e02ab7b6-9431-11e7-904d-62d8ae8c9f8b.GIF)
[Test Log Form Enhancement #001.docx](https://github.com/richardz316/vmcs/files/1285591/Test.Log.Form.Enhancement.001.docx)

**Comment by jarongoh** [comment]
Issue was reopened to include screenshots and Test Log attachments for Enhancement #001.

**Comment by smitabisoyi** [comment]
Closing the issue as verification is already done.
