### ISSUE TITLE
Bug: Does not clear values upon completion of maintenance

### ISSUE THREAD

**Issue by yeojc** [richardz316/vmcs#2]
Reset the values to null for “Show Total Cash Held” and “Press to Collect Cash” when the
Maintainer successfully pushes “Press Here When Finished”. The simulation currently does
not clear the values on the completion of a Maintenance session. Upon a subsequent re-login
to the Maintenance Panel in the same session, the cash previously held and already collected,
persists in display. This sometimes causes confusion to Maintainer.

**Comment by richardz316** [comment]
<Impact Analysis>
01. Cause of issue: 
Both collect cash and total cash are not initialized upon logout the Maintenance Panel. 
02. Resolution:
Add logic in MaintenanceController.java to initialize the collect cash and total cash when logout the Maintenance Panel.

**Comment by bendanye** [comment]
i have fixed the bug. Please verify

**Comment by jarongoh** [comment]
Bug fix has been verified.

Attached are Test Log Forms and Test Results.

Please validate

![defect01](https://user-images.githubusercontent.com/17529208/30175261-7a328246-9430-11e7-8078-2b70b83c00f0.jpg)

[Test Log Form Defect #002.docx](https://github.com/richardz316/vmcs/files/1286224/Test.Log.Form.Defect.002.docx)

**Comment by smitabisoyi** [comment]
Verified the fix.

**Comment by jarongoh** [comment]
Screenshots and Test Logs for Enhancement Issue #001 was removed
